/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SpeciesIdImport } from './routes/$speciesId'
import { Route as IndexImport } from './routes/index'
import { Route as SpeciesIdGroupsImport } from './routes/$speciesId.groups'
import { Route as SpeciesIdGroupsGroupIdImport } from './routes/$speciesId.groups.$groupId'

// Create/Update Routes

const SpeciesIdRoute = SpeciesIdImport.update({
  path: '/$speciesId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SpeciesIdGroupsRoute = SpeciesIdGroupsImport.update({
  path: '/groups',
  getParentRoute: () => SpeciesIdRoute,
} as any)

const SpeciesIdGroupsGroupIdRoute = SpeciesIdGroupsGroupIdImport.update({
  path: '/$groupId',
  getParentRoute: () => SpeciesIdGroupsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$speciesId': {
      preLoaderRoute: typeof SpeciesIdImport
      parentRoute: typeof rootRoute
    }
    '/$speciesId/groups': {
      preLoaderRoute: typeof SpeciesIdGroupsImport
      parentRoute: typeof SpeciesIdImport
    }
    '/$speciesId/groups/$groupId': {
      preLoaderRoute: typeof SpeciesIdGroupsGroupIdImport
      parentRoute: typeof SpeciesIdGroupsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  SpeciesIdRoute.addChildren([
    SpeciesIdGroupsRoute.addChildren([SpeciesIdGroupsGroupIdRoute]),
  ]),
])

/* prettier-ignore-end */
